#!/usr/bin/env node
/**
 * Generate web/src/lib/company_tickers.generated.ts from config/company_tickers.yaml
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import yaml from "yaml";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "../..");
const CONFIG = path.join(ROOT, "config/company_tickers.yaml");
const OUT = path.resolve(__dirname, "../src/lib/company_tickers.generated.ts");

const data = yaml.parse(fs.readFileSync(CONFIG, "utf8"));
const aliases = data.aliases || {};
const tickerAliases = data.ticker_aliases || {};

function escapeString(value) {
  return JSON.stringify(String(value));
}

const aliasLines = Object.entries(aliases)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([key, ticker]) => `  ${escapeString(key)}: ${escapeString(ticker)},`)
  .join("\n");

const tickerAliasLines = Object.entries(tickerAliases)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([key, ticker]) => `  ${escapeString(String(key).toUpperCase())}: ${escapeString(ticker)},`)
  .join("\n");

const contents = `/* eslint-disable */
// Generated by web/scripts/generate-tickers.mjs — do not edit.
// Source: config/company_tickers.yaml

export const COMPANY_ALIASES: Record<string, string> = {
${aliasLines}
};

export const TICKER_ALIASES: Record<string, string> = {
${tickerAliasLines}
};
`;

fs.writeFileSync(OUT, contents);
console.log(`Generated ${path.relative(ROOT, OUT)}`);
