#!/usr/bin/env python3
"""Seed metadata-only approved JSON for 20 new Chinese podcast episodes (batch 6)."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ZH = ROOT / "data" / "approved" / "zh"
EN = ROOT / "data" / "approved"

ZJ_POD = "https://www.xiaoyuzhoufm.com/podcast/626b46ea9cbbf0451cf5a962"
TZS_POD = "https://www.xiaoyuzhoufm.com/podcast/643cdf1ad3d94ec2ad39ae94"
ZJ_APPLE = "https://podcasts.apple.com/cn/podcast/id1634356920"
TZS_APPLE = "https://podcasts.apple.com/cn/podcast/id1718660227"


def _placeholder_body(ticker: str = "GOOGL") -> dict:
    return {
        "conclusion": "占位",
        "background": "占位",
        "important_facts": ["占位"],
        "mental_model": {"name": "占位", "components": "占位", "application": "占位"},
        "key_insights": [{"view": "占位", "question": "占位", "answer": "占位"}],
        "top_investment_implications": [
            {"ticker": ticker, "direction": "Watch", "confidence": "Low", "thesis": "占位"}
        ],
        "golden_quotes": ["占位"],
        "chronology": {"subject": "占位", "events": [{"date": "2026", "event": "占位"}]},
    }


def _en_placeholder_body(ticker: str = "GOOGL") -> dict:
    return {
        "conclusion": "placeholder",
        "background": "placeholder",
        "important_facts": ["placeholder"],
        "mental_model": {"name": "placeholder", "components": "placeholder", "application": "placeholder"},
        "key_insights": [{"view": "placeholder", "question": "placeholder", "answer": "placeholder"}],
        "top_investment_implications": [
            {"ticker": ticker, "direction": "Watch", "confidence": "Low", "thesis": "placeholder"}
        ],
        "golden_quotes": ["placeholder"],
        "chronology": {"subject": "placeholder", "events": [{"date": "2026", "event": "placeholder"}]},
    }


def _links(youtube: str | None = None) -> dict:
    links = {"apple_podcasts": ZJ_APPLE, "xiaoyuzhou": ZJ_POD}
    if youtube:
        links["youtube"] = youtube
    return links


def _tzs_links(youtube: str | None = None) -> dict:
    links = {"apple_podcasts": TZS_APPLE, "xiaoyuzhou": TZS_POD}
    if youtube:
        links["youtube"] = youtube
    return links


EPISODES = {
    "zj-ep115": {
        "zh": {
            "episode_id": "zj-ep115",
            "podcast": "张小珺商业访谈录",
            "host": "张小珺",
            "metadata": {
                "episode_number": 115,
                "title": "对OpenAI姚顺雨3小时访谈：6年Agent研究、人与系统、吞噬的边界、既单极又多元的世界",
                "guest": "姚顺雨",
                "guest_role": "OpenAI研究员（访谈时）",
                "date": "2025-04-19",
                "duration_minutes": 180,
                "youtube_url": "https://www.youtube.com/watch?v=gQgKkUsx5q0",
                "links": _links("https://www.youtube.com/watch?v=gQgKkUsx5q0"),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["GOOGL", "OpenAI", "Agent", "RL"],
            **_placeholder_body("GOOGL"),
        },
        "en": {
            "episode_id": "zj-ep115",
            "podcast": "Zhang Xiaojun Podcast",
            "host": "Zhang Xiaojun",
            "metadata": {
                "episode_number": 115,
                "title": "3-Hour Interview with Yao Shunyu (OpenAI): Six Years of Agent Research, Humans & Systems",
                "guest": "Yao Shunyu",
                "guest_role": "OpenAI Researcher (at time of interview)",
                "date": "2025-04-19",
                "duration_minutes": 180,
                "youtube_url": "https://www.youtube.com/watch?v=gQgKkUsx5q0",
                "links": _links("https://www.youtube.com/watch?v=gQgKkUsx5q0"),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["GOOGL", "OpenAI", "Agent", "RL"],
            **_en_placeholder_body("GOOGL"),
        },
    },
    "zj-ep70": {
        "zh": {
            "episode_id": "zj-ep70",
            "podcast": "张小珺商业访谈录",
            "host": "张小珺",
            "metadata": {
                "episode_number": 70,
                "title": "和何小鹏聊，FSD、“在血海游泳”、乱世中的英雄与狗熊",
                "guest": "何小鹏",
                "guest_role": "小鹏汽车董事长兼CEO",
                "date": "2024-07-15",
                "duration_minutes": 90,
                "youtube_url": "",
                "links": _links(),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["XPEV", "TSLA", "FSD", "智驾"],
            **_placeholder_body("XPEV"),
        },
        "en": {
            "episode_id": "zj-ep70",
            "podcast": "Zhang Xiaojun Podcast",
            "host": "Zhang Xiaojun",
            "metadata": {
                "episode_number": 70,
                "title": "He Xiaopeng on FSD, Swimming in a Sea of Blood, Heroes and Cowards in Chaos",
                "guest": "He Xiaopeng",
                "guest_role": "XPeng Chairman & CEO",
                "date": "2024-07-15",
                "duration_minutes": 90,
                "youtube_url": "",
                "links": _links(),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["XPEV", "TSLA", "FSD", "AD"],
            **_en_placeholder_body("XPEV"),
        },
    },
    "zj-ep87": {
        "zh": {
            "episode_id": "zj-ep87",
            "podcast": "张小珺商业访谈录",
            "host": "张小珺",
            "metadata": {
                "episode_number": 87,
                "title": "对李想的3小时访谈（播客版）：宅男、AI、家庭、游戏和天梯",
                "guest": "李想",
                "guest_role": "理想汽车创始人兼CEO",
                "date": "2025-01-02",
                "duration_minutes": 180,
                "youtube_url": "https://www.youtube.com/watch?v=mbiPeZnmz9A",
                "links": _links("https://www.youtube.com/watch?v=mbiPeZnmz9A"),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["LI", "AI", "FSD", "MEGA"],
            **_placeholder_body("LI"),
        },
        "en": {
            "episode_id": "zj-ep87",
            "podcast": "Zhang Xiaojun Podcast",
            "host": "Zhang Xiaojun",
            "metadata": {
                "episode_number": 87,
                "title": "3-Hour Podcast Cut with Li Xiang: Otaku, AI, Family, Games and Ladder",
                "guest": "Li Xiang",
                "guest_role": "Li Auto Founder & CEO",
                "date": "2025-01-02",
                "duration_minutes": 180,
                "youtube_url": "https://www.youtube.com/watch?v=mbiPeZnmz9A",
                "links": _links("https://www.youtube.com/watch?v=mbiPeZnmz9A"),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["LI", "AI", "FSD", "MEGA"],
            **_en_placeholder_body("LI"),
        },
    },
    "zj-ep79": {
        "zh": {
            "episode_id": "zj-ep79",
            "podcast": "张小珺商业访谈录",
            "host": "张小珺",
            "metadata": {
                "episode_number": 79,
                "title": "特斯拉股价跌了，Uber却涨了？漫谈特斯拉Robotaxi大会",
                "guest": "孟醒",
                "guest_role": "自动驾驶创业者、技术不无聊主播",
                "date": "2024-10-13",
                "duration_minutes": 59,
                "youtube_url": "https://www.youtube.com/watch?v=_nqR-T5tl-M",
                "links": _links("https://www.youtube.com/watch?v=_nqR-T5tl-M"),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["TSLA", "UBER", "Robotaxi", "FSD"],
            **_placeholder_body("TSLA"),
        },
        "en": {
            "episode_id": "zj-ep79",
            "podcast": "Zhang Xiaojun Podcast",
            "host": "Zhang Xiaojun",
            "metadata": {
                "episode_number": 79,
                "title": "Tesla Stock Fell, Uber Rose? Robotaxi Event Debrief with Meng Xing",
                "guest": "Meng Xing",
                "guest_role": "Autonomous Driving Founder, Tech Podcast Host",
                "date": "2024-10-13",
                "duration_minutes": 59,
                "youtube_url": "https://www.youtube.com/watch?v=_nqR-T5tl-M",
                "links": _links("https://www.youtube.com/watch?v=_nqR-T5tl-M"),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["TSLA", "UBER", "Robotaxi", "FSD"],
            **_en_placeholder_body("TSLA"),
        },
    },
    "zj-ep72": {
        "zh": {
            "episode_id": "zj-ep72",
            "podcast": "张小珺商业访谈录",
            "host": "张小珺",
            "metadata": {
                "episode_number": 72,
                "title": "从蒸汽机到无人驾驶3｜和孟醒聊特斯拉FSD进化史",
                "guest": "孟醒",
                "guest_role": "自动驾驶创业者",
                "date": "2024-08-18",
                "duration_minutes": 75,
                "youtube_url": "https://www.youtube.com/watch?v=uTj7nDasNGg",
                "links": _links("https://www.youtube.com/watch?v=uTj7nDasNGg"),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["TSLA", "FSD", "端到端", "自动驾驶"],
            **_placeholder_body("TSLA"),
        },
        "en": {
            "episode_id": "zj-ep72",
            "podcast": "Zhang Xiaojun Podcast",
            "host": "Zhang Xiaojun",
            "metadata": {
                "episode_number": 72,
                "title": "Steam Engine to Self-Driving 3: Meng Xing on Tesla FSD Evolution",
                "guest": "Meng Xing",
                "guest_role": "Autonomous Driving Founder",
                "date": "2024-08-18",
                "duration_minutes": 75,
                "youtube_url": "https://www.youtube.com/watch?v=uTj7nDasNGg",
                "links": _links("https://www.youtube.com/watch?v=uTj7nDasNGg"),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["TSLA", "FSD", "End-to-End", "Autonomous Driving"],
            **_en_placeholder_body("TSLA"),
        },
    },
    "zj-ep94": {
        "zh": {
            "episode_id": "zj-ep94",
            "podcast": "张小珺商业访谈录",
            "host": "张小珺",
            "metadata": {
                "episode_number": 94,
                "title": "逐篇讲解DeepSeek、Kimi、MiniMax注意力机制新论文——“硬件上的暴力美学”",
                "guest": "广密",
                "guest_role": "AI研究员、全球大模型季报主播",
                "date": "2025-03-02",
                "duration_minutes": 90,
                "youtube_url": "https://www.youtube.com/watch?v=42CveqxzU5M",
                "links": _links("https://www.youtube.com/watch?v=42CveqxzU5M"),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["NVDA", "DeepSeek", "Kimi", "MiniMax"],
            **_placeholder_body("NVDA"),
        },
        "en": {
            "episode_id": "zj-ep94",
            "podcast": "Zhang Xiaojun Podcast",
            "host": "Zhang Xiaojun",
            "metadata": {
                "episode_number": 94,
                "title": "DeepSeek, Kimi, MiniMax Attention Papers: Hardware Brute-Force Aesthetics",
                "guest": "Guangmi",
                "guest_role": "AI Researcher, LLM Quarterly Host",
                "date": "2025-03-02",
                "duration_minutes": 90,
                "youtube_url": "https://www.youtube.com/watch?v=42CveqxzU5M",
                "links": _links("https://www.youtube.com/watch?v=42CveqxzU5M"),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["NVDA", "DeepSeek", "Kimi", "MiniMax"],
            **_en_placeholder_body("NVDA"),
        },
    },
    "zj-ep93": {
        "zh": {
            "episode_id": "zj-ep93",
            "podcast": "张小珺商业访谈录",
            "host": "张小珺",
            "metadata": {
                "episode_number": 93,
                "title": "离开字节、MiniMax的张前川，发出AGI对人类威胁的预警",
                "guest": "张前川",
                "guest_role": "前今日头条用户产品负责人、前MiniMax产品负责人",
                "date": "2025-02-20",
                "duration_minutes": 127,
                "youtube_url": "https://www.youtube.com/watch?v=hBEOntt_pxM",
                "links": _links("https://www.youtube.com/watch?v=hBEOntt_pxM"),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["META", "TCEHY", "AGI", "推荐引擎"],
            **_placeholder_body("META"),
        },
        "en": {
            "episode_id": "zj-ep93",
            "podcast": "Zhang Xiaojun Podcast",
            "host": "Zhang Xiaojun",
            "metadata": {
                "episode_number": 93,
                "title": "Zhang Qianchuan on Leaving ByteDance & MiniMax: AGI Threat Warning",
                "guest": "Zhang Qianchuan",
                "guest_role": "Former ByteDance Toutiao Product Head, Former MiniMax Product Head",
                "date": "2025-02-20",
                "duration_minutes": 127,
                "youtube_url": "https://www.youtube.com/watch?v=hBEOntt_pxM",
                "links": _links("https://www.youtube.com/watch?v=hBEOntt_pxM"),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["META", "TCEHY", "AGI", "Recommendation Engine"],
            **_en_placeholder_body("META"),
        },
    },
    "zj-ep89": {
        "zh": {
            "episode_id": "zj-ep89",
            "podcast": "张小珺商业访谈录",
            "host": "张小珺",
            "metadata": {
                "episode_number": 89,
                "title": "逐句讲解DeepSeek-R1、Kimi K1.5、OpenAI o1技术报告——“最优美的算法最干净”",
                "guest": "广密",
                "guest_role": "AI研究员",
                "date": "2025-01-26",
                "duration_minutes": 85,
                "youtube_url": "https://www.youtube.com/watch?v=0AImqp6KznY",
                "links": _links("https://www.youtube.com/watch?v=0AImqp6KznY"),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["GOOGL", "DeepSeek-R1", "o1", "推理"],
            **_placeholder_body("GOOGL"),
        },
        "en": {
            "episode_id": "zj-ep89",
            "podcast": "Zhang Xiaojun Podcast",
            "host": "Zhang Xiaojun",
            "metadata": {
                "episode_number": 89,
                "title": "DeepSeek-R1, Kimi K1.5, OpenAI o1 Reports: Cleanest Algorithms",
                "guest": "Guangmi",
                "guest_role": "AI Researcher",
                "date": "2025-01-26",
                "duration_minutes": 85,
                "youtube_url": "https://www.youtube.com/watch?v=0AImqp6KznY",
                "links": _links("https://www.youtube.com/watch?v=0AImqp6KznY"),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["GOOGL", "DeepSeek-R1", "o1", "Reasoning"],
            **_en_placeholder_body("GOOGL"),
        },
    },
    "zj-ep88": {
        "zh": {
            "episode_id": "zj-ep88",
            "podcast": "张小珺商业访谈录",
            "host": "张小珺",
            "metadata": {
                "episode_number": 88,
                "title": "和吴翼技术解读OpenAI Operator：推理从抽象世界走向物理世界的开端",
                "guest": "吴翼",
                "guest_role": "OpenAI前研究员、清华大学助理教授",
                "date": "2025-01-19",
                "duration_minutes": 72,
                "youtube_url": "https://www.youtube.com/watch?v=usv9yyA0bs0",
                "links": _links("https://www.youtube.com/watch?v=usv9yyA0bs0"),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["GOOGL", "OpenAI", "Operator", "Agent"],
            **_placeholder_body("GOOGL"),
        },
        "en": {
            "episode_id": "zj-ep88",
            "podcast": "Zhang Xiaojun Podcast",
            "host": "Zhang Xiaojun",
            "metadata": {
                "episode_number": 88,
                "title": "Wu Yi on OpenAI Operator: Reasoning Enters the Physical World",
                "guest": "Wu Yi",
                "guest_role": "Former OpenAI Researcher, Tsinghua Assistant Professor",
                "date": "2025-01-19",
                "duration_minutes": 72,
                "youtube_url": "https://www.youtube.com/watch?v=usv9yyA0bs0",
                "links": _links("https://www.youtube.com/watch?v=usv9yyA0bs0"),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["GOOGL", "OpenAI", "Operator", "Agent"],
            **_en_placeholder_body("GOOGL"),
        },
    },
    "zj-ep75": {
        "zh": {
            "episode_id": "zj-ep75",
            "podcast": "张小珺商业访谈录",
            "host": "张小珺",
            "metadata": {
                "episode_number": 75,
                "title": "和OpenAI前研究员吴翼解读o1：吹响了开挖第二座金矿的号角",
                "guest": "吴翼",
                "guest_role": "OpenAI前研究员、清华大学助理教授",
                "date": "2024-09-22",
                "duration_minutes": 68,
                "youtube_url": "https://www.youtube.com/watch?v=8fDHQAVWInI",
                "links": _links("https://www.youtube.com/watch?v=8fDHQAVWInI"),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["GOOGL", "o1", "推理", "OpenAI"],
            **_placeholder_body("GOOGL"),
        },
        "en": {
            "episode_id": "zj-ep75",
            "podcast": "Zhang Xiaojun Podcast",
            "host": "Zhang Xiaojun",
            "metadata": {
                "episode_number": 75,
                "title": "Wu Yi on OpenAI o1: The Second Gold Mine",
                "guest": "Wu Yi",
                "guest_role": "Former OpenAI Researcher, Tsinghua Assistant Professor",
                "date": "2024-09-22",
                "duration_minutes": 68,
                "youtube_url": "https://www.youtube.com/watch?v=8fDHQAVWInI",
                "links": _links("https://www.youtube.com/watch?v=8fDHQAVWInI"),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["GOOGL", "o1", "Reasoning", "OpenAI"],
            **_en_placeholder_body("GOOGL"),
        },
    },
    "tzs-ep155": {
        "zh": {
            "episode_id": "tzs-ep155",
            "podcast": "投资实战派",
            "host": "永庆 & 大卫",
            "metadata": {
                "episode_number": 155,
                "title": "吃吃喝喝背后的投资洞察，西贝、海底捞、蜜雪、小菜园、茅台…",
                "guest": "大卫",
                "guest_role": "投资实战派主理人",
                "date": "2025-11-02",
                "duration_minutes": 99,
                "youtube_url": "",
                "links": _tzs_links(),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["600519.SZ", "消费", "餐饮", "茅台"],
            **_placeholder_body("600519.SZ"),
        },
        "en": {
            "episode_id": "tzs-ep155",
            "podcast": "Practical Investments",
            "host": "Yongqing & David",
            "metadata": {
                "episode_number": 155,
                "title": "Investment Insights Behind Dining: Xibei, Haidilao, Mixue, Moutai…",
                "guest": "David",
                "guest_role": "Practical Investments Host",
                "date": "2025-11-02",
                "duration_minutes": 99,
                "youtube_url": "",
                "links": _tzs_links(),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["600519.SZ", "Consumer", "Dining", "Moutai"],
            **_en_placeholder_body("600519.SZ"),
        },
    },
    "tzs-ep127": {
        "zh": {
            "episode_id": "tzs-ep127",
            "podcast": "投资实战派",
            "host": "永庆 & 大卫",
            "metadata": {
                "episode_number": 127,
                "title": "老铺黄金：古法工艺溢价or智商税？| 畅聊新消费",
                "guest": "杨禹琦、叶子、小欧",
                "guest_role": "消费投资人与消费者嘉宾",
                "date": "2025-06-15",
                "duration_minutes": 119,
                "youtube_url": "",
                "links": _tzs_links(),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["6181.HK", "老铺黄金", "新消费", "奢侈品"],
            **_placeholder_body("6181.HK"),
        },
        "en": {
            "episode_id": "tzs-ep127",
            "podcast": "Practical Investments",
            "host": "Yongqing & David",
            "metadata": {
                "episode_number": 127,
                "title": "Laopu Gold: Heritage Craft Premium or IQ Tax? | New Consumer Chat",
                "guest": "Yang Yuqi, Ye Zi, Xiao Ou",
                "guest_role": "Consumer Investors & Consumer Guests",
                "date": "2025-06-15",
                "duration_minutes": 119,
                "youtube_url": "",
                "links": _tzs_links(),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["6181.HK", "Laopu Gold", "New Consumer", "Luxury"],
            **_en_placeholder_body("6181.HK"),
        },
    },
    "tzs-ep125": {
        "zh": {
            "episode_id": "tzs-ep125",
            "podcast": "投资实战派",
            "host": "永庆 & 大卫",
            "metadata": {
                "episode_number": 125,
                "title": "独特的泡泡玛特：美丽的泡泡or塑料茅台?｜畅聊新消费系列",
                "guest": "大卫",
                "guest_role": "投资实战派主理人",
                "date": "2025-06-05",
                "duration_minutes": 108,
                "youtube_url": "",
                "links": _tzs_links(),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["9992.HK", "泡泡玛特", "IP", "潮玩"],
            **_placeholder_body("9992.HK"),
        },
        "en": {
            "episode_id": "tzs-ep125",
            "podcast": "Practical Investments",
            "host": "Yongqing & David",
            "metadata": {
                "episode_number": 125,
                "title": "Pop Mart: Beautiful Bubble or Plastic Moutai? | New Consumer Series",
                "guest": "David",
                "guest_role": "Practical Investments Host",
                "date": "2025-06-05",
                "duration_minutes": 108,
                "youtube_url": "",
                "links": _tzs_links(),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["9992.HK", "Pop Mart", "IP", "Art Toys"],
            **_en_placeholder_body("9992.HK"),
        },
    },
    "tzs-ep133": {
        "zh": {
            "episode_id": "tzs-ep133",
            "podcast": "投资实战派",
            "host": "永庆 & 大卫",
            "metadata": {
                "episode_number": 133,
                "title": "东鹏饮料，逆势高成长，有何不同？｜畅聊新消费系列",
                "guest": "大卫",
                "guest_role": "投资实战派主理人",
                "date": "2025-07-10",
                "duration_minutes": 88,
                "youtube_url": "",
                "links": _tzs_links(),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["605499.SH", "东鹏饮料", "功能饮料", "新消费"],
            **_placeholder_body("605499.SH"),
        },
        "en": {
            "episode_id": "tzs-ep133",
            "podcast": "Practical Investments",
            "host": "Yongqing & David",
            "metadata": {
                "episode_number": 133,
                "title": "Eastroc Beverage: Counter-Cyclical Growth — What's Different?",
                "guest": "David",
                "guest_role": "Practical Investments Host",
                "date": "2025-07-10",
                "duration_minutes": 88,
                "youtube_url": "",
                "links": _tzs_links(),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["605499.SH", "Eastroc Beverage", "Energy Drink", "New Consumer"],
            **_en_placeholder_body("605499.SH"),
        },
    },
    "tzs-ep130": {
        "zh": {
            "episode_id": "tzs-ep130",
            "podcast": "投资实战派",
            "host": "永庆 & 大卫",
            "metadata": {
                "episode_number": 130,
                "title": "二十四年All in的茅台人生｜对话张亚群",
                "guest": "张亚群",
                "guest_role": "茅台经销商、24年茅台从业者",
                "date": "2025-06-29",
                "duration_minutes": 56,
                "youtube_url": "",
                "links": _tzs_links(),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["600519.SZ", "茅台", "白酒", "渠道"],
            **_placeholder_body("600519.SZ"),
        },
        "en": {
            "episode_id": "tzs-ep130",
            "podcast": "Practical Investments",
            "host": "Yongqing & David",
            "metadata": {
                "episode_number": 130,
                "title": "24 Years All-In on Moutai: A Life in Kweichow Moutai | Zhang Yaqun",
                "guest": "Zhang Yaqun",
                "guest_role": "Moutai Distributor, 24-Year Industry Veteran",
                "date": "2025-06-29",
                "duration_minutes": 56,
                "youtube_url": "",
                "links": _tzs_links(),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["600519.SZ", "Moutai", "Baijiu", "Distribution"],
            **_en_placeholder_body("600519.SZ"),
        },
    },
    "tzs-ep128": {
        "zh": {
            "episode_id": "tzs-ep128",
            "podcast": "投资实战派",
            "host": "永庆 & 大卫",
            "metadata": {
                "episode_number": 128,
                "title": "从算力战争到国产替代：智驾芯片的下一个爆点与坑点｜对话王康、罗慧超",
                "guest": "王康、罗慧超",
                "guest_role": "智驾芯片产业专家",
                "date": "2025-06-22",
                "duration_minutes": 105,
                "youtube_url": "",
                "links": _tzs_links(),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["NVDA", "9660.HK", "智驾芯片", "国产替代"],
            **_placeholder_body("NVDA"),
        },
        "en": {
            "episode_id": "tzs-ep128",
            "podcast": "Practical Investments",
            "host": "Yongqing & David",
            "metadata": {
                "episode_number": 128,
                "title": "Compute War to Domestic Chips: AD Chip Booms and Traps",
                "guest": "Wang Kang, Luo Huichao",
                "guest_role": "Autonomous Driving Chip Industry Experts",
                "date": "2025-06-22",
                "duration_minutes": 105,
                "youtube_url": "",
                "links": _tzs_links(),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["NVDA", "9660.HK", "AD Chips", "Domestic Substitution"],
            **_en_placeholder_body("NVDA"),
        },
    },
    "tzs-ep116": {
        "zh": {
            "episode_id": "tzs-ep116",
            "podcast": "投资实战派",
            "host": "永庆 & 大卫",
            "metadata": {
                "episode_number": 116,
                "title": "如何投资高增长科技股？25年经验的美股分析师投资框架",
                "guest": "永庆",
                "guest_role": "投资实战派嘉宾、美股分析师",
                "date": "2025-05-05",
                "duration_minutes": 75,
                "youtube_url": "",
                "links": _tzs_links(),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["NVDA", "GOOGL", "科技股", "成长投资"],
            **_placeholder_body("NVDA"),
        },
        "en": {
            "episode_id": "tzs-ep116",
            "podcast": "Practical Investments",
            "host": "Yongqing & David",
            "metadata": {
                "episode_number": 116,
                "title": "How to Invest in High-Growth Tech: 25-Year US Equity Analyst Framework",
                "guest": "Yongqing",
                "guest_role": "Practical Investments Guest, US Equity Analyst",
                "date": "2025-05-05",
                "duration_minutes": 75,
                "youtube_url": "",
                "links": _tzs_links(),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["NVDA", "GOOGL", "Tech Stocks", "Growth Investing"],
            **_en_placeholder_body("NVDA"),
        },
    },
    "tzs-ep166": {
        "zh": {
            "episode_id": "tzs-ep166",
            "podcast": "投资实战派",
            "host": "永庆 & 大卫",
            "metadata": {
                "episode_number": 166,
                "title": "消费和互联网，25年深度复盘与26年展望 | David对谈产业专家小X老师",
                "guest": "小X老师",
                "guest_role": "消费与互联网产业专家",
                "date": "2026-01-12",
                "duration_minutes": 97,
                "youtube_url": "",
                "links": _tzs_links(),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["BABA", "PDD", "消费互联网", "复盘"],
            **_placeholder_body("BABA"),
        },
        "en": {
            "episode_id": "tzs-ep166",
            "podcast": "Practical Investments",
            "host": "Yongqing & David",
            "metadata": {
                "episode_number": 166,
                "title": "Consumer & Internet: 25-Year Review and 2026 Outlook",
                "guest": "Teacher X",
                "guest_role": "Consumer & Internet Industry Expert",
                "date": "2026-01-12",
                "duration_minutes": 97,
                "youtube_url": "",
                "links": _tzs_links(),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["BABA", "PDD", "Consumer Internet", "Review"],
            **_en_placeholder_body("BABA"),
        },
    },
    "tzs-ep165": {
        "zh": {
            "episode_id": "tzs-ep165",
            "podcast": "投资实战派",
            "host": "永庆 & 大卫",
            "metadata": {
                "episode_number": 165,
                "title": "消费品投资：白酒、休闲食品的“用户价值”与“渠道革命”| 永庆对谈马铮",
                "guest": "马铮",
                "guest_role": "消费品投资专家",
                "date": "2026-01-04",
                "duration_minutes": 85,
                "youtube_url": "",
                "links": _tzs_links(),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["600519.SZ", "白酒", "休闲食品", "渠道"],
            **_placeholder_body("600519.SZ"),
        },
        "en": {
            "episode_id": "tzs-ep165",
            "podcast": "Practical Investments",
            "host": "Yongqing & David",
            "metadata": {
                "episode_number": 165,
                "title": "Consumer Investing: Baijiu & Snacks — User Value and Channel Revolution",
                "guest": "Ma Zheng",
                "guest_role": "Consumer Investment Expert",
                "date": "2026-01-04",
                "duration_minutes": 85,
                "youtube_url": "",
                "links": _tzs_links(),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["600519.SZ", "Baijiu", "Snacks", "Distribution"],
            **_en_placeholder_body("600519.SZ"),
        },
    },
    "tzs-ep137": {
        "zh": {
            "episode_id": "tzs-ep137",
            "podcast": "投资实战派",
            "host": "永庆 & 大卫",
            "metadata": {
                "episode_number": 137,
                "title": "农夫山泉、美的、安踏背后的消费品渠道制胜密码|对话文永生",
                "guest": "文永生",
                "guest_role": "消费品渠道专家",
                "date": "2025-07-24",
                "duration_minutes": 104,
                "youtube_url": "",
                "links": _tzs_links(),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["9633.HK", "2020.HK", "000333.SZ", "渠道"],
            **_placeholder_body("9633.HK"),
        },
        "en": {
            "episode_id": "tzs-ep137",
            "podcast": "Practical Investments",
            "host": "Yongqing & David",
            "metadata": {
                "episode_number": 137,
                "title": "Channel Secrets Behind Nongfu, Midea & Anta | Wen Yongsheng",
                "guest": "Wen Yongsheng",
                "guest_role": "Consumer Distribution Expert",
                "date": "2025-07-24",
                "duration_minutes": 104,
                "youtube_url": "",
                "links": _tzs_links(),
            },
            "episode_rating": {"overall": 3},
            "keywords": ["9633.HK", "2020.HK", "000333.SZ", "Distribution"],
            **_en_placeholder_body("9633.HK"),
        },
    },
}

if __name__ == "__main__":
    ZH.mkdir(parents=True, exist_ok=True)
    for eid, pair in EPISODES.items():
        (ZH / f"{eid}.json").write_text(
            json.dumps(pair["zh"], ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )
        (EN / f"{eid}.json").write_text(
            json.dumps(pair["en"], ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )
        print(f"wrote {eid}")
