#!/usr/bin/env python3
"""Seed metadata-only approved JSON for 6 new Chinese podcast episodes."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ZH = ROOT / "data" / "approved" / "zh"
EN = ROOT / "data" / "approved"

ZJ_POD = "https://www.xiaoyuzhoufm.com/podcast/626b46ea9cbbf0451cf5a962"
TZS_POD = "https://www.xiaoyuzhoufm.com/podcast/643cdf1ad3d94ec2ad39ae94"
ZJ_APPLE = "https://podcasts.apple.com/cn/podcast/id1634356920"
TZS_APPLE = "https://podcasts.apple.com/cn/podcast/id1718660227"

EPISODES = {
    "zj-ep141": {
        "zh": {
            "episode_id": "zj-ep141",
            "podcast": "张小珺商业访谈录",
            "host": "张小珺",
            "metadata": {
                "episode_number": 141,
                "title": "Freda的投资札记第2集：Tokenmaxxing、把电机塞进蒸汽机、接力赛变篮球赛",
                "guest": "Freda",
                "guest_role": "Lightspeed Venture Partners 合伙人",
                "date": "2026-05-18",
                "duration_minutes": 84,
                "youtube_url": "https://www.youtube.com/watch?v=MjTfhm5N8x8",
                "links": {
                    "youtube": "https://www.youtube.com/watch?v=MjTfhm5N8x8",
                    "apple_podcasts": ZJ_APPLE,
                    "xiaoyuzhou": ZJ_POD,
                },
            },
            "episode_rating": {"overall": 5},
            "keywords": ["GOOGL", "META", "Token 经济学", "AI 组织变革"],
            "conclusion": "占位",
            "background": "占位",
            "important_facts": ["占位"],
            "mental_model": {"name": "占位", "components": "占位", "application": "占位"},
            "key_insights": [{"view": "占位", "question": "占位", "answer": "占位"}],
            "top_investment_implications": [{"ticker": "GOOGL", "direction": "Watch", "confidence": "Low", "thesis": "占位"}],
            "golden_quotes": ["占位"],
            "chronology": {"subject": "Freda", "events": [{"date": "2026", "event": "占位"}]},
        },
        "en": {
            "episode_id": "zj-ep141",
            "podcast": "Zhang Xiaojun Podcast",
            "host": "Zhang Xiaojun",
            "metadata": {
                "episode_number": 141,
                "title": "Freda's Investment Notes Ep.2: Tokenmaxxing, Motors in Steam Engines, Relay to Basketball",
                "guest": "Freda",
                "guest_role": "Partner, Lightspeed Venture Partners",
                "date": "2026-05-18",
                "duration_minutes": 84,
                "youtube_url": "https://www.youtube.com/watch?v=MjTfhm5N8x8",
                "links": {
                    "youtube": "https://www.youtube.com/watch?v=MjTfhm5N8x8",
                    "apple_podcasts": ZJ_APPLE,
                    "xiaoyuzhou": ZJ_POD,
                },
            },
            "episode_rating": {"overall": 5},
            "keywords": ["GOOGL", "META", "Token Economics", "AI Org Design"],
            "conclusion": "placeholder",
            "background": "placeholder",
            "important_facts": ["placeholder"],
            "mental_model": {"name": "placeholder", "components": "placeholder", "application": "placeholder"},
            "key_insights": [{"view": "placeholder", "question": "placeholder", "answer": "placeholder"}],
            "top_investment_implications": [{"ticker": "GOOGL", "direction": "Watch", "confidence": "Low", "thesis": "placeholder"}],
            "golden_quotes": ["placeholder"],
            "chronology": {"subject": "Freda", "events": [{"date": "2026", "event": "placeholder"}]},
        },
    },
    "zj-ep142": {
        "zh": {
            "episode_id": "zj-ep142",
            "podcast": "张小珺商业访谈录",
            "host": "张小珺",
            "metadata": {
                "episode_number": 142,
                "title": "雨森的创投观察第2集：Harness、下一个字节、2026大机会和Stanley Druckenmiller",
                "guest": "雨森",
                "guest_role": "创投观察者",
                "date": "2026-05-27",
                "duration_minutes": 139,
                "youtube_url": "https://www.youtube.com/watch?v=XEhf371Aeso",
                "links": {
                    "youtube": "https://www.youtube.com/watch?v=XEhf371Aeso",
                    "apple_podcasts": ZJ_APPLE,
                    "xiaoyuzhou": ZJ_POD,
                },
            },
            "episode_rating": {"overall": 5},
            "keywords": ["Private:Harness", "字节跳动", "2026 创投"],
            "conclusion": "占位",
            "background": "占位",
            "important_facts": ["占位"],
            "mental_model": {"name": "占位", "components": "占位", "application": "占位"},
            "key_insights": [{"view": "占位", "question": "占位", "answer": "占位"}],
            "top_investment_implications": [{"ticker": "Private:Harness", "direction": "Watch", "confidence": "Low", "thesis": "占位"}],
            "golden_quotes": ["占位"],
            "chronology": {"subject": "雨森", "events": [{"date": "2026", "event": "占位"}]},
        },
        "en": {
            "episode_id": "zj-ep142",
            "podcast": "Zhang Xiaojun Podcast",
            "host": "Zhang Xiaojun",
            "metadata": {
                "episode_number": 142,
                "title": "Yusen's VC Watch Ep.2: Harness, Next ByteDance, 2026 Opportunities & Stanley Druckenmiller",
                "guest": "Yusen",
                "guest_role": "Venture Capital Observer",
                "date": "2026-05-27",
                "duration_minutes": 139,
                "youtube_url": "https://www.youtube.com/watch?v=XEhf371Aeso",
                "links": {
                    "youtube": "https://www.youtube.com/watch?v=XEhf371Aeso",
                    "apple_podcasts": ZJ_APPLE,
                    "xiaoyuzhou": ZJ_POD,
                },
            },
            "episode_rating": {"overall": 5},
            "keywords": ["Private:Harness", "ByteDance", "2026 VC Themes"],
            "conclusion": "placeholder",
            "background": "placeholder",
            "important_facts": ["placeholder"],
            "mental_model": {"name": "placeholder", "components": "placeholder", "application": "placeholder"},
            "key_insights": [{"view": "placeholder", "question": "placeholder", "answer": "placeholder"}],
            "top_investment_implications": [{"ticker": "Private:Harness", "direction": "Watch", "confidence": "Low", "thesis": "placeholder"}],
            "golden_quotes": ["placeholder"],
            "chronology": {"subject": "Yusen", "events": [{"date": "2026", "event": "placeholder"}]},
        },
    },
    "zj-ep145": {
        "zh": {
            "episode_id": "zj-ep145",
            "podcast": "张小珺商业访谈录",
            "host": "张小珺",
            "metadata": {
                "episode_number": 145,
                "title": "口述SpaceX开发史：和前高管洪力德聊，马斯克用人观、最大IPO、太空与AI",
                "guest": "洪力德",
                "guest_role": "SpaceX 前高管",
                "date": "2026-06-12",
                "duration_minutes": 181,
                "youtube_url": "https://www.youtube.com/watch?v=ABtf0yehi1I",
                "links": {
                    "youtube": "https://www.youtube.com/watch?v=ABtf0yehi1I",
                    "apple_podcasts": ZJ_APPLE,
                    "xiaoyuzhou": ZJ_POD,
                },
            },
            "episode_rating": {"overall": 5},
            "keywords": ["Private:SpaceX", "TSLA", "太空经济"],
            "conclusion": "占位",
            "background": "占位",
            "important_facts": ["占位"],
            "mental_model": {"name": "占位", "components": "占位", "application": "占位"},
            "key_insights": [{"view": "占位", "question": "占位", "answer": "占位"}],
            "top_investment_implications": [{"ticker": "TSLA", "direction": "Watch", "confidence": "Low", "thesis": "占位"}],
            "golden_quotes": ["占位"],
            "chronology": {"subject": "洪力德 · SpaceX", "events": [{"date": "2026", "event": "占位"}]},
        },
        "en": {
            "episode_id": "zj-ep145",
            "podcast": "Zhang Xiaojun Podcast",
            "host": "Zhang Xiaojun",
            "metadata": {
                "episode_number": 145,
                "title": "Oral History of SpaceX: Ex-Executive Hong Lide on Musk's Hiring, Mega-IPO, Space & AI",
                "guest": "Hong Lide",
                "guest_role": "Former SpaceX Executive",
                "date": "2026-06-12",
                "duration_minutes": 181,
                "youtube_url": "https://www.youtube.com/watch?v=ABtf0yehi1I",
                "links": {
                    "youtube": "https://www.youtube.com/watch?v=ABtf0yehi1I",
                    "apple_podcasts": ZJ_APPLE,
                    "xiaoyuzhou": ZJ_POD,
                },
            },
            "episode_rating": {"overall": 5},
            "keywords": ["Private:SpaceX", "TSLA", "Space Economy"],
            "conclusion": "placeholder",
            "background": "placeholder",
            "important_facts": ["placeholder"],
            "mental_model": {"name": "placeholder", "components": "placeholder", "application": "placeholder"},
            "key_insights": [{"view": "placeholder", "question": "placeholder", "answer": "placeholder"}],
            "top_investment_implications": [{"ticker": "TSLA", "direction": "Watch", "confidence": "Low", "thesis": "placeholder"}],
            "golden_quotes": ["placeholder"],
            "chronology": {"subject": "Hong Lide · SpaceX", "events": [{"date": "2026", "event": "placeholder"}]},
        },
    },
    "tzs-ep184": {
        "zh": {
            "episode_id": "tzs-ep184",
            "podcast": "投资实战派",
            "host": "永庆 & 大卫",
            "metadata": {
                "episode_number": 184,
                "title": "治愈癌症？CAR-T细胞疗法的科学与商业",
                "guest": "李宗海、齐长松",
                "guest_role": "科济药业CEO、临床专家",
                "date": "2026-05-24",
                "duration_minutes": 108,
                "youtube_url": "https://www.youtube.com/watch?v=YGy8A_KWWNM",
                "links": {
                    "youtube": "https://www.youtube.com/watch?v=YGy8A_KWWNM",
                    "apple_podcasts": TZS_APPLE,
                    "xiaoyuzhou": TZS_POD,
                },
            },
            "episode_rating": {"overall": 5},
            "keywords": ["2171.HK", "CAR-T", "创新药"],
            "conclusion": "占位",
            "background": "占位",
            "important_facts": ["占位"],
            "mental_model": {"name": "占位", "components": "占位", "application": "占位"},
            "key_insights": [{"view": "占位", "question": "占位", "answer": "占位"}],
            "top_investment_implications": [{"ticker": "2171.HK", "direction": "Watch", "confidence": "Low", "thesis": "占位"}],
            "golden_quotes": ["占位"],
            "chronology": {"subject": "CAR-T · 科济药业", "events": [{"date": "2026", "event": "占位"}]},
        },
        "en": {
            "episode_id": "tzs-ep184",
            "podcast": "Practical Investments",
            "host": "Yongqing & David",
            "metadata": {
                "episode_number": 184,
                "title": "Curing Cancer? CAR-T Cell Therapy — Science and Business",
                "guest": "Li Zonghai, Qi Changsong",
                "guest_role": "CARsgen CEO, Clinical Expert",
                "date": "2026-05-24",
                "duration_minutes": 108,
                "youtube_url": "https://www.youtube.com/watch?v=YGy8A_KWWNM",
                "links": {
                    "youtube": "https://www.youtube.com/watch?v=YGy8A_KWWNM",
                    "apple_podcasts": TZS_APPLE,
                    "xiaoyuzhou": TZS_POD,
                },
            },
            "episode_rating": {"overall": 5},
            "keywords": ["2171.HK", "CAR-T", "Innovative Drugs"],
            "conclusion": "placeholder",
            "background": "placeholder",
            "important_facts": ["placeholder"],
            "mental_model": {"name": "placeholder", "components": "placeholder", "application": "placeholder"},
            "key_insights": [{"view": "placeholder", "question": "placeholder", "answer": "placeholder"}],
            "top_investment_implications": [{"ticker": "2171.HK", "direction": "Watch", "confidence": "Low", "thesis": "placeholder"}],
            "golden_quotes": ["placeholder"],
            "chronology": {"subject": "CAR-T · CARsgen", "events": [{"date": "2026", "event": "placeholder"}]},
        },
    },
    "tzs-ep186": {
        "zh": {
            "episode_id": "tzs-ep186",
            "podcast": "投资实战派",
            "host": "永庆 & 大卫",
            "metadata": {
                "episode_number": 186,
                "title": "市场分化的选择：狂飙追光赌行情or稳健价值守本金？",
                "guest": "永庆、沈帅波",
                "guest_role": "投资实战派联合创始人、消费观察家",
                "date": "2026-06-07",
                "duration_minutes": 90,
                "youtube_url": "https://www.youtube.com/watch?v=Fko6aJvRC4c",
                "links": {
                    "youtube": "https://www.youtube.com/watch?v=Fko6aJvRC4c",
                    "apple_podcasts": TZS_APPLE,
                    "xiaoyuzhou": TZS_POD,
                },
            },
            "episode_rating": {"overall": 5},
            "keywords": ["价值投资", "市场分化", "仓位管理"],
            "conclusion": "占位",
            "background": "占位",
            "important_facts": ["占位"],
            "mental_model": {"name": "占位", "components": "占位", "application": "占位"},
            "key_insights": [{"view": "占位", "question": "占位", "answer": "占位"}],
            "top_investment_implications": [{"ticker": "BRK.B", "direction": "Long", "confidence": "Low", "thesis": "占位"}],
            "golden_quotes": ["占位"],
            "chronology": {"subject": "永庆 · 市场分化", "events": [{"date": "2026", "event": "占位"}]},
        },
        "en": {
            "episode_id": "tzs-ep186",
            "podcast": "Practical Investments",
            "host": "Yongqing & David",
            "metadata": {
                "episode_number": 186,
                "title": "Divergent Markets: Chase Momentum or Guard Principal with Value?",
                "guest": "Yongqing, Shen Shuaibo",
                "guest_role": "Practical Investments Co-founder, Consumer Observer",
                "date": "2026-06-07",
                "duration_minutes": 90,
                "youtube_url": "https://www.youtube.com/watch?v=Fko6aJvRC4c",
                "links": {
                    "youtube": "https://www.youtube.com/watch?v=Fko6aJvRC4c",
                    "apple_podcasts": TZS_APPLE,
                    "xiaoyuzhou": TZS_POD,
                },
            },
            "episode_rating": {"overall": 5},
            "keywords": ["Value Investing", "Market Divergence", "Position Sizing"],
            "conclusion": "placeholder",
            "background": "placeholder",
            "important_facts": ["placeholder"],
            "mental_model": {"name": "placeholder", "components": "placeholder", "application": "placeholder"},
            "key_insights": [{"view": "placeholder", "question": "placeholder", "answer": "placeholder"}],
            "top_investment_implications": [{"ticker": "BRK.B", "direction": "Long", "confidence": "Low", "thesis": "placeholder"}],
            "golden_quotes": ["placeholder"],
            "chronology": {"subject": "Yongqing · Market Divergence", "events": [{"date": "2026", "event": "placeholder"}]},
        },
    },
    "tzs-ep187": {
        "zh": {
            "episode_id": "tzs-ep187",
            "podcast": "投资实战派",
            "host": "永庆 & 大卫",
            "metadata": {
                "episode_number": 187,
                "title": "AI时代，我们如何成为「不可替代的人」？",
                "guest": "姜讯",
                "guest_role": "AI 与职业成长专家",
                "date": "2026-06-15",
                "duration_minutes": 93,
                "youtube_url": "https://www.youtube.com/watch?v=4VuTBcjEI9g",
                "links": {
                    "youtube": "https://www.youtube.com/watch?v=4VuTBcjEI9g",
                    "apple_podcasts": TZS_APPLE,
                    "xiaoyuzhou": TZS_POD,
                },
            },
            "episode_rating": {"overall": 5},
            "keywords": ["AI 职业", "不可替代性", "人力资本"],
            "conclusion": "占位",
            "background": "占位",
            "important_facts": ["占位"],
            "mental_model": {"name": "占位", "components": "占位", "application": "占位"},
            "key_insights": [{"view": "占位", "question": "占位", "answer": "占位"}],
            "top_investment_implications": [{"ticker": "GOOGL", "direction": "Watch", "confidence": "Low", "thesis": "占位"}],
            "golden_quotes": ["占位"],
            "chronology": {"subject": "姜讯 · AI 时代职业", "events": [{"date": "2026", "event": "占位"}]},
        },
        "en": {
            "episode_id": "tzs-ep187",
            "podcast": "Practical Investments",
            "host": "Yongqing & David",
            "metadata": {
                "episode_number": 187,
                "title": "In the AI Era, How Do We Become Irreplaceable?",
                "guest": "Jiang Xun",
                "guest_role": "AI & Career Development Expert",
                "date": "2026-06-15",
                "duration_minutes": 93,
                "youtube_url": "https://www.youtube.com/watch?v=4VuTBcjEI9g",
                "links": {
                    "youtube": "https://www.youtube.com/watch?v=4VuTBcjEI9g",
                    "apple_podcasts": TZS_APPLE,
                    "xiaoyuzhou": TZS_POD,
                },
            },
            "episode_rating": {"overall": 5},
            "keywords": ["AI Careers", "Irreplaceability", "Human Capital"],
            "conclusion": "placeholder",
            "background": "placeholder",
            "important_facts": ["placeholder"],
            "mental_model": {"name": "placeholder", "components": "placeholder", "application": "placeholder"},
            "key_insights": [{"view": "placeholder", "question": "placeholder", "answer": "placeholder"}],
            "top_investment_implications": [{"ticker": "GOOGL", "direction": "Watch", "confidence": "Low", "thesis": "placeholder"}],
            "golden_quotes": ["placeholder"],
            "chronology": {"subject": "Jiang Xun · AI-Era Careers", "events": [{"date": "2026", "event": "placeholder"}]},
        },
    },
}

if __name__ == "__main__":
    ZH.mkdir(parents=True, exist_ok=True)
    for eid, pair in EPISODES.items():
        (ZH / f"{eid}.json").write_text(json.dumps(pair["zh"], ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        (EN / f"{eid}.json").write_text(json.dumps(pair["en"], ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(f"wrote {eid}")
